logging:
  level:
    com.hhb: debug
server:
  port: 8080
spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.0.30.6:3306/xlxl?autoReconnect=true&useSSL=false
      username: root
      password: Admin@123
mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
  type-aliases-package: com.hhb.pojo
  mapper-locations: classpath:mapper/*.xml

